# from dotenv import load_dotenv
# import os

# load_dotenv()

# OIDC_CLIENT_ID = os.getenv("OIDC_CLIENT_ID")
# OIDC_CLIENT_SECRET = os.getenv("OIDC_CLIENT_SECRET")
# OIDC_ISSUER_URL = os.getenv("OIDC_ISSUER_URL")
# KEYCLOAK_SERVER_URL = os.getenv("KEYCLOAK_SERVER_URL")
# OIDC_REDIRECT_URI = os.getenv("OIDC_REDIRECT_URI")
# OIDC_DISCOVERY_SERVER = os.getenv("OIDC_DISCOVERY_SERVER")
# OIDC_AUTHORIZATION_URL = f"{OIDC_ISSUER_URL}/authorize"
# OIDC_TOKEN_URL = f"{OIDC_ISSUER_URL}/token"
# OIDC_USERINFO_URL = f"{OIDC_ISSUER_URL}/userinfo"
# OIDC_TOKEN_INTROSPECTION_URI= f"{OIDC_ISSUER_URL}/introspect"
# OIDC_DISCOVERY_URL = f"{OIDC_ISSUER_URL}/.well-known/openid-configuration"
# KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM")

# CMP_LOOKUP_USER_URL = os.getenv("CMP_LOOKUP_USER_URL")
# CMP_LOOKUP_USER_TOKEN = os.getenv("CMP_LOOKUP_USER_TOKEN")